# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UiPathTest@6
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'UiPath Test Orchestrator'
    projectKey: 'DEMO'
    testSet: 'DEMO:606'
    folderName: 'Global/Projects/Agentic Testing POC'
    skipResultsPublishing: true
    attachRobotLogs: true
